name: MB
settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"

options:
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

configs:
  Debug: debug
  Release: release

targets:
  MB:
    platform: iOS
    type: application
    deploymentTarget: "17.0"
    sources: [MB]

    settings:
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PRODUCT_BUNDLE_IDENTIFIER: br.com.wagnersales.MB
      INFOPLIST_FILE: MB/Info.plist

  MBTests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - path: MBTests

    dependencies:
      - target: MB  

schemes:
  MB:
    build:
      targets:
        MB: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - MB
      targets:
        - MBTests
