name: API
settings:
  MARKETING_VERSION: "1.0.0"
  SWIFT_VERSION: 5.0
  VERSIONING_SYSTEM: "apple-generic"
  CODE_SIGN_IDENTITY: "iPhone Developer"
  CLANG_ENABLE_OBJC_WEAK: "YES"
  ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: "YES"

options:
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "17.0"

configs:
  Debug: debug
  Release: release

targets:
  API:
    platform: iOS
    type: framework

    sources:
      - path: API

    settings:
      CODE_SIGN_STYLE: "Manual"
      DEVELOPMENT_TEAM: ""
      PRODUCT_BUNDLE_IDENTIFIER: br.com.wagnersales.API
      INFOPLIST_FILE: API/Info.plist

      ENABLE_BITCODE: "YES"
      TARGETED_DEVICE_FAMILY: "1"
      ARCHS: "$(ARCHS_STANDARD)"
      LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"

  APITests:
    platform: iOS
    type: bundle.unit-test

    sources:
      - path: APITests

    dependencies:
      - target: API

schemes:
  API:
    build:
      targets:
        API: [run, test]
      parallelizeBuild: true
      buildImplicitDependencies: true

    run:
      config: Debug

    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - API
      targets:
        - APITests